stages:
  prepare_data:
    cmd: .venv\Scripts\python.exe -c "from src.train_model import download_crypto_data, save_cached_data; data = download_crypto_data(); save_cached_data(data)"
    deps:
      - src/train_model.py
    outs:
      - models/btc_hourly_cache.csv

  train_model:
    cmd: set MLFLOW_TRACKING_URI=file:./mlruns && set MLFLOW_ARTIFACT_URI= && .venv\Scripts\python.exe -u src/train_model.py
    deps:
      - src/train_model.py
      - models/btc_hourly_cache.csv
    outs:
      - models/lstm_btc_hourly.keras
      - models/scaler_btc.gz
      - models/scaler_btc_return.gz
    metrics:
      - models/model_metadata_btc.json:
          cache: false