name: CI (Pull Requests)

on:
  pull_request:
    branches:
      - main
      - develop
      - release

concurrency:
  group: ci-pr-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/ci_common.yml
    secrets: inherit
